## uav properties
uav:
 mass: 1.0
 inertia: [0.029, 0.029, 0.055]
 arm_length: 0.255
 max_rotor_speed: 1100
 min_rotor_speed: 50
 rotor_constant: 5.84e-06
 rotor_moment_constant: 0.06
 mission: 0
 test_mode: 0

controller:
 position_p: { x: 8, y: 8, z: 6 }
 position_Kp1: { x: 4, y: 4, z: 4 }
 position_Kp2: { x: 0.01, y: 0.01, z: 0.02 }
 gamma_1: 0.015
 position_sigma: 0.02
 attitude_p: { x: 0.02, y: 0.02, z: 0.04 }
 attitude_Kphi1: { x: 0.05, y: 0.05, z: 0.2 }
 attitude_Kphi2: { x: 0.001, y: 0.001, z: 0.001 }
 gamma_bb: { x: 0.0001, y: 0.0001, z: 0.0001 }
 attitude_sigma: 0.05

estimator:
 K_f: {x: 2.5, y: 2.5, z: 3}
 estimator_enable: 1

constrain:
 tilt_max_angle: 30

release:
 idle_thrust: 0.11
 release_thrust: 0.25
 release_rate_z: 0.2
 max_rate_yaw: 1.0

docking:
  position: {x: -0.03, y: -0.61, z: 0.8}
  docking_final_altitude: 1.07

morph:
 max_angle: 140
 min_angle: 140
 morphing_start_time: 24
 morphing_time: 2